sudo: false

language: scala
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.m2

jdk:
- openjdk8

script:
  - sbt +test

matrix:
  include:
    - env: PLAY_VERSION=2.5
    - env: PLAY_VERSION=2.6
    - env: PLAY_VERSION=2.7
